export const FETCH_PENDING = 'FETCH_PENDING';
export const FETCH_COMPLETE = 'FETCH_COMPLETE';
export const FETCH_FAILED = 'FETCH_FAILED';
export const REMOVE_PENDING = 'REMOVE_PENDING';
export const REMOVE_COMPLETE = 'REMOVE_COMPLETE';
export const REMOVE_FAILED = 'REMOVE_FAILED';

export const TOGGLE_RIGHT_MENU = 'TOGGLE_RIGHT_MENU';
export const TOGGLE_LEFT_MENU = 'TOGGLE_LEFT_MENU';
